/**
 * Intelligence Moat addendum - F6 Partnership Matching Engine (pure layer).
 *
 * Deterministic scoring of candidate partners against a source entity. The db /
 * route layer loads the source entity attributes, the candidate pool, and the
 * relationship-edge strengths; this module scores each candidate 0..100 and
 * explains why, with no DB access, no AI, and no randomness.
 *
 * match(entityType, entityId, targetKind, ctx) ranks candidates by a COMPOSITE:
 *   a fit score (location, budget, audience, capacity, capabilities, historical
 *   success, industry, availability, revenue, relationship strength) blended with
 *   the candidate's cached Divini Score and owning-org Business Health, so the
 *   recomputed trust/performance signals actually drive the ranking. The blend is
 *   deterministic and explainable: each match returns its weighted components.
 *
 * Pairings supported (source -> targetKind):
 *   venue   -> vendor | sponsor
 *   vendor  -> client | venue
 *   planner -> venue
 *   agency  -> vendor
 *   sponsor -> venue   (sponsor looking for venues / events to activate at)
 *   brand   -> venue   (brand looking for an audience match)
 */

export type MatchEntityType =
  | "venue"
  | "vendor"
  | "planner"
  | "agency"
  | "sponsor"
  | "brand"
  | "client";

export type TargetKind = "vendor" | "sponsor" | "client" | "venue";

/** Normalized attributes for either the source entity or a candidate. */
export type MatchEntity = {
  id: string;
  kind: MatchEntityType | TargetKind;
  name?: string | null;
  city?: string | null;
  region?: string | null;
  category?: string | null;
  capabilities?: string[] | null; // services / subcategories / amenities
  industry?: string | null;
  audience_size?: number | null;
  capacity?: number | null;
  budget?: number | null; // typical budget or price band
  review_score?: number | null; // 0..5 historical success proxy
  available?: boolean | null; // availability flag (true/unknown = ok)
  revenue?: number | null; // historical revenue with / generated by this entity
  divini_score?: number | null; // 0..100 cached Divini Score (lib/diviniScore.ts)
  business_health?: number | null; // 0..100 owning org Business Health (lib/businessHealth.ts)
};

/** Context the db layer assembles for a single match() call. */
export type MatchContext = {
  source: MatchEntity;
  candidates: MatchEntity[];
  /** edgeStrength[candidateId] = aggregate relationship weight to the source. */
  edgeStrength?: Record<string, number>;
  /** edgeRevenue[candidateId] = aggregate revenue on edges to the source. */
  edgeRevenue?: Record<string, number>;
};

/**
 * One weighted contribution to the final composite score, returned so the UI can
 * explain "why this match" (each part is already weight-applied, 0..100 scale).
 */
export type MatchScoreComponent = {
  key: "fit" | "divini_score" | "business_health";
  label: string;
  weight: number; // 0..1 share of the final blend this component carries
  value: number; // the component's own 0..100 value before weighting
  contribution: number; // weight * value, the points this part adds to `score`
};

export type PartnershipMatch = {
  candidate: MatchEntity;
  score: number; // 0..100 composite (fit blended with Divini Score + health)
  fit: number; // 0..100 fit-only score (location/capability/budget/trust signals)
  reasons: string[];
  components: MatchScoreComponent[]; // explainable breakdown of the composite
};

/**
 * Composite blend weights. The fit score (location, capability, budget, capacity,
 * audience, review track record, revenue, relationship strength) is the backbone;
 * the Divini Score and Business Health overlay the candidate's proven, recomputed
 * trust/performance so a strong-on-paper-but-weakly-rated partner ranks below a
 * comparable, better-scored one. Weights sum to 1. The two intelligence overlays
 * are "graceful-absent": when a candidate has no cached Divini Score / health, its
 * weight folds back into fit so the candidate is ranked on fit alone (never
 * penalized for missing intelligence). Same inputs -> same blend (deterministic).
 */
export const MATCH_BLEND_WEIGHTS = {
  fit: 0.6,
  divini_score: 0.3,
  business_health: 0.1,
} as const;

const clamp = (n: number, lo: number, hi: number): number => (n < lo ? lo : n > hi ? hi : n);
const num = (n: number | null | undefined): number =>
  typeof n === "number" && Number.isFinite(n) ? n : 0;
const norm = (s?: string | null): string => (s ?? "").trim().toLowerCase();

function overlap(a?: string[] | null, b?: string[] | null): number {
  const A = new Set((a ?? []).map(norm).filter(Boolean));
  if (A.size === 0) return 0;
  const B = new Set((b ?? []).map(norm).filter(Boolean));
  let hit = 0;
  for (const x of A) if (B.has(x)) hit++;
  return hit / A.size; // 0..1 share of source capabilities covered
}

/**
 * Score one candidate against the source. Each signal contributes a bounded
 * number of points; the total is clamped to 0..100. Same inputs -> same score.
 */
export function scoreMatch(
  source: MatchEntity,
  cand: MatchEntity,
  edgeStrength = 0,
  edgeRevenue = 0,
): PartnershipMatch {
  const reasons: string[] = [];
  let score = 0;

  // Location: same city is strongest, same region next.
  if (norm(source.city) && norm(source.city) === norm(cand.city)) {
    score += 18;
    reasons.push(`Same city (${cand.city})`);
  } else if (norm(source.region) && norm(source.region) === norm(cand.region)) {
    score += 11;
    reasons.push(`Same region (${cand.region})`);
  }

  // Capabilities / category fit.
  const cov = overlap(source.capabilities, cand.capabilities);
  if (cov > 0) {
    const pts = Math.round(cov * 16);
    score += pts;
    reasons.push(`Covers ${Math.round(cov * 100)}% of needed capabilities`);
  }
  if (norm(source.category) && norm(source.category) === norm(cand.category)) {
    score += 6;
    reasons.push(`Matching category (${cand.category})`);
  }

  // Industry alignment.
  if (norm(source.industry) && norm(source.industry) === norm(cand.industry)) {
    score += 8;
    reasons.push(`Same industry (${cand.industry})`);
  }

  // Audience match (sponsor/brand <-> venue): closeness of audience sizes.
  const aS = num(source.audience_size);
  const aC = num(cand.audience_size);
  if (aS > 0 && aC > 0) {
    const ratio = Math.min(aS, aC) / Math.max(aS, aC);
    const pts = Math.round(ratio * 10);
    score += pts;
    if (ratio >= 0.6) reasons.push(`Audience size aligns (~${aC.toLocaleString("en-US")})`);
  }

  // Capacity fit: candidate venue can hold the source's expected count.
  const need = num(source.capacity) || num(source.audience_size);
  const cap = num(cand.capacity);
  if (need > 0 && cap > 0) {
    if (cap >= need) {
      score += 8;
      reasons.push(`Capacity fits (${cap.toLocaleString("en-US")} >= ${need.toLocaleString("en-US")})`);
    } else if (cap >= need * 0.8) {
      score += 4;
      reasons.push("Capacity is close to requirement");
    }
  }

  // Budget fit: candidate price band within the source budget.
  const bS = num(source.budget);
  const bC = num(cand.budget);
  if (bS > 0 && bC > 0) {
    if (bC <= bS) {
      score += 8;
      reasons.push("Within budget");
    } else if (bC <= bS * 1.15) {
      score += 4;
      reasons.push("Near budget");
    }
  }

  // Historical success (review score, 0..5).
  const rev = clamp(num(cand.review_score), 0, 5);
  if (rev > 0) {
    const pts = Math.round((rev / 5) * 10);
    score += pts;
    if (rev >= 4) reasons.push(`Strong track record (${rev.toFixed(1)}/5)`);
  }

  // Availability.
  if (cand.available === true) {
    score += 5;
    reasons.push("Currently available");
  } else if (cand.available === false) {
    score -= 6;
    reasons.push("Limited availability");
  }

  // Revenue history (candidate has generated revenue in the ecosystem).
  const candRevenue = num(cand.revenue) + num(edgeRevenue);
  if (candRevenue > 0) {
    const pts = Math.min(8, Math.round(Math.log10(candRevenue + 1) * 2));
    score += pts;
    if (candRevenue >= 5000)
      reasons.push(`Proven revenue ($${Math.round(candRevenue).toLocaleString("en-US")})`);
  }

  // Relationship strength (existing edges between source and candidate).
  const e = num(edgeStrength);
  if (e > 0) {
    const pts = Math.min(12, e * 3);
    score += pts;
    reasons.push(`Existing relationship (${e} prior ${e === 1 ? "link" : "links"})`);
  }

  // The fit score: everything above (location/capability/budget/capacity/audience/
  // review track record/revenue/relationship), clamped to 0..100.
  const fit = clamp(Math.round(score), 0, 100);

  // ---- Composite blend: fold the computed-but-previously-unconsumed Divini Score
  // and Business Health into the ranking. Each overlay is graceful-absent: when a
  // candidate has no cached value its weight redistributes onto the remaining
  // present components (always including fit), so a candidate is never penalized
  // for missing intelligence and the present weights always renormalize to 1.
  const hasDivini = cand.divini_score != null && Number.isFinite(Number(cand.divini_score));
  const hasHealth =
    cand.business_health != null && Number.isFinite(Number(cand.business_health));
  const diviniVal = hasDivini ? clamp(Number(cand.divini_score), 0, 100) : 0;
  const healthVal = hasHealth ? clamp(Number(cand.business_health), 0, 100) : 0;

  let activeWeight = MATCH_BLEND_WEIGHTS.fit;
  if (hasDivini) activeWeight += MATCH_BLEND_WEIGHTS.divini_score;
  if (hasHealth) activeWeight += MATCH_BLEND_WEIGHTS.business_health;
  const renorm = activeWeight > 0 ? 1 / activeWeight : 1;

  const components: MatchScoreComponent[] = [];
  const round2 = (n: number): number => Math.round(n * 100) / 100;

  const fitWeight = MATCH_BLEND_WEIGHTS.fit * renorm;
  components.push({
    key: "fit",
    label: "Fit",
    weight: round2(fitWeight),
    value: fit,
    contribution: round2(fitWeight * fit),
  });
  if (hasDivini) {
    const w = MATCH_BLEND_WEIGHTS.divini_score * renorm;
    components.push({
      key: "divini_score",
      label: "Divini Score",
      weight: round2(w),
      value: diviniVal,
      contribution: round2(w * diviniVal),
    });
    if (diviniVal >= 75) reasons.push(`High Divini Score (${diviniVal})`);
    else if (diviniVal > 0 && diviniVal < 45) reasons.push(`Low Divini Score (${diviniVal})`);
  }
  if (hasHealth) {
    const w = MATCH_BLEND_WEIGHTS.business_health * renorm;
    components.push({
      key: "business_health",
      label: "Business health",
      weight: round2(w),
      value: healthVal,
      contribution: round2(w * healthVal),
    });
    if (healthVal >= 75) reasons.push(`Healthy business (${healthVal})`);
  }

  const composite = clamp(
    Math.round(components.reduce((s, c) => s + c.contribution, 0)),
    0,
    100,
  );

  return { candidate: cand, score: composite, fit, reasons, components };
}

/**
 * Rank all candidates for the given source. Deterministic ordering: score desc,
 * then review_score desc, then id ascending for a stable tiebreak.
 */
export function match(
  _entityType: MatchEntityType,
  _entityId: string,
  _targetKind: TargetKind,
  ctx: MatchContext,
): PartnershipMatch[] {
  const strength = ctx.edgeStrength ?? {};
  const revenue = ctx.edgeRevenue ?? {};
  const scored = ctx.candidates
    .filter((c) => c.id !== ctx.source.id)
    .map((c) => scoreMatch(ctx.source, c, strength[c.id] ?? 0, revenue[c.id] ?? 0));
  return scored.sort(
    (a, b) =>
      b.score - a.score ||
      num(b.candidate.divini_score) - num(a.candidate.divini_score) ||
      num(b.candidate.review_score) - num(a.candidate.review_score) ||
      (a.candidate.id < b.candidate.id ? -1 : a.candidate.id > b.candidate.id ? 1 : 0),
  );
}

/** Which concrete table a targetKind resolves to (used by the db layer). */
export const TARGET_KINDS: TargetKind[] = ["vendor", "sponsor", "client", "venue"];
