import { Router, type IRouter } from "express";
import healthRouter from "./health";
import partnersRouter from "./partners";
import partnerEmailRecipientsRouter from "./partnerEmailRecipients";
import publicPortalRouter from "./publicPortal";
import requestsRouter from "./requests";
import pricingRouter from "./pricing";
import dashboardRouter from "./dashboard";
import storageRouter from "./storage";
import partnerThemesRouter from "./partnerThemes";
import partnerSectionsRouter from "./partnerSections";
import productCatalogRouter from "./productCatalog";
import brandingLocationsRouter from "./brandingLocations";
import portalRequestsRouter from "./portalRequests";
import deckExtractionRouter from "./deckExtraction";
import suppliersRouter from "./suppliers";
import citiesRouter from "./cities";
import venuesRouter from "./venues";
import eventsRouter from "./events";
import packagesRouter from "./packages";
import inventoryRouter from "./inventory";
import quoteAssetsRouter from "./quoteAssets";
import ordersRouter from "./orders";
import userRolesRouter from "./userRoles";
import savedAddressesRouter from "./savedAddresses";
import partnerOnboardingRouter from "./partnerOnboarding";
import { assetsRouter } from "./assets";
import { productionRouter } from "./production";
import workflowRouter from "./workflow";
import analyticsRouter from "./analytics";
import onboardingRouter from "./onboarding";
import postLaunchRouter from "./postLaunch";
import commercializationRouter from "./commercialization";
import salesEnablementRouter from "./salesEnablement";
import stabilizationRouter from "./stabilization";
import deploymentRouter from "./deployment";
import unitsRouter from "./units";
import partnerInventoryRouter from "./partnerInventory";
import exportsRouter from "./exports";
import reconciliationRouter from "./reconciliation";
import invoicesRouter from "./invoices";
import billingRouter from "./billing";
import publicConfigRouter from "./publicConfig";

const router: IRouter = Router();

router.use(healthRouter);
router.use(publicConfigRouter);
router.use(partnersRouter);
router.use(partnerEmailRecipientsRouter);
router.use(publicPortalRouter);
router.use(requestsRouter);
router.use(pricingRouter);
router.use(dashboardRouter);
router.use(storageRouter);
router.use(partnerThemesRouter);
router.use(partnerSectionsRouter);
router.use(productCatalogRouter);
router.use(brandingLocationsRouter);
router.use(portalRequestsRouter);
router.use(deckExtractionRouter);
router.use(suppliersRouter);
router.use(citiesRouter);
router.use(venuesRouter);
router.use(eventsRouter);
router.use(packagesRouter);
router.use(inventoryRouter);
router.use(quoteAssetsRouter);
router.use(ordersRouter);
router.use(userRolesRouter);
router.use(savedAddressesRouter);
router.use(partnerOnboardingRouter);
router.use(partnerInventoryRouter);
router.use(exportsRouter);
router.use(reconciliationRouter);
router.use(invoicesRouter);
router.use(billingRouter);
router.use(assetsRouter);
router.use(productionRouter);
router.use(workflowRouter);
router.use(analyticsRouter);
router.use(onboardingRouter);
router.use(postLaunchRouter);
router.use(commercializationRouter);
router.use(salesEnablementRouter);
router.use(stabilizationRouter);
router.use(deploymentRouter);
router.use(unitsRouter);

export default router;
