import { Router, type IRouter } from "express";
import healthRouter from "./health";
import partnersRouter from "./partners";
import publicPortalRouter from "./publicPortal";
import requestsRouter from "./requests";
import pricingRouter from "./pricing";
import dashboardRouter from "./dashboard";
import storageRouter from "./storage";
import partnerThemesRouter from "./partnerThemes";
import partnerSectionsRouter from "./partnerSections";
import productCatalogRouter from "./productCatalog";
import brandingLocationsRouter from "./brandingLocations";
import portalRequestsRouter from "./portalRequests";
import deckExtractionRouter from "./deckExtraction";
import suppliersRouter from "./suppliers";
import citiesRouter from "./cities";
import venuesRouter from "./venues";
import eventsRouter from "./events";
import packagesRouter from "./packages";
import inventoryRouter from "./inventory";
import quoteAssetsRouter from "./quoteAssets";
import ordersRouter from "./orders";
import userRolesRouter from "./userRoles";
import savedAddressesRouter from "./savedAddresses";
import partnerOnboardingRouter from "./partnerOnboarding";
import partnerInventoryRouter from "./partnerInventory";

const router: IRouter = Router();

router.use(healthRouter);
router.use(partnersRouter);
router.use(publicPortalRouter);
router.use(requestsRouter);
router.use(pricingRouter);
router.use(dashboardRouter);
router.use(storageRouter);
router.use(partnerThemesRouter);
router.use(partnerSectionsRouter);
router.use(productCatalogRouter);
router.use(brandingLocationsRouter);
router.use(portalRequestsRouter);
router.use(deckExtractionRouter);
router.use(suppliersRouter);
router.use(citiesRouter);
router.use(venuesRouter);
router.use(eventsRouter);
router.use(packagesRouter);
router.use(inventoryRouter);
router.use(quoteAssetsRouter);
router.use(ordersRouter);
router.use(userRolesRouter);
router.use(savedAddressesRouter);
router.use(partnerOnboardingRouter);
router.use(partnerInventoryRouter);

export default router;
