import React, { useEffect, useState } from 'react';
import { apiGet, apiSend } from '../lib/api';

/**
 * Divini Follow-Up Desk - prevents leads and proposals from being forgotten
 * (docs/DIVINI_DETERMINISTIC_TOOLS_SPEC.md). System tasks are generated by
 * fixed, explainable rules against real Pipeline and Proposal Studio data
 * (never a guess); manual tasks are entirely user-controlled.
 */

type Status = 'open' | 'done' | 'snoozed' | 'dismissed';
type Task = {
  id: string;
  source: 'manual' | 'system';
  rule_key: string | null;
  title: string;
  note: string | null;
  due_at: string | null;
  status: Status;
  snoozed_until: string | null;
  opportunity_id: string | null;
  proposal_id: string | null;
};

const RULE_LABEL: Record<string, string> = {
  opportunity_next_action_overdue: 'Next action overdue',
  opportunity_stale: 'No recent activity',
  proposal_unresponded: 'Proposal not yet answered',
  proposal_expiring: 'Proposal expiring soon',
};

function dueLabel(t: Task): string | null {
  if (!t.due_at) return null;
  const d = new Date(t.due_at);
  const overdue = d.getTime() < Date.now();
  return `${overdue ? 'Was due' : 'Due'} ${d.toLocaleDateString()}`;
}

const EMPTY_FORM = { title: '', note: '', due_at: '' };

export default function FollowUpDesk() {
  const [tasks, setTasks] = useState<Task[]>([]);
  const [loading, setLoading] = useState(true);
  const [error, setError] = useState<string | null>(null);
  const [creating, setCreating] = useState(false);
  const [form, setForm] = useState(EMPTY_FORM);
  const [busy, setBusy] = useState<string | null>(null);

  async function load() {
    setLoading(true);
    setError(null);
    try {
      const r = await apiGet<{ tasks: Task[] }>('/follow-up-desk/tasks');
      setTasks(r.tasks);
    } catch (e) {
      setError((e as Error).message);
    } finally {
      setLoading(false);
    }
  }
  useEffect(() => { void load(); }, []);

  async function create(e: React.FormEvent) {
    e.preventDefault();
    if (!form.title.trim()) return;
    setBusy('create');
    setError(null);
    try {
      await apiSend('POST', '/follow-up-desk/tasks', {
        title: form.title.trim(),
        note: form.note.trim() || undefined,
        due_at: form.due_at || undefined,
      });
      setForm(EMPTY_FORM);
      setCreating(false);
      await load();
    } catch (e) {
      setError((e as Error).message);
    } finally {
      setBusy(null);
    }
  }

  async function markDone(id: string) {
    setBusy(id);
    try {
      await apiSend('POST', `/follow-up-desk/tasks/${id}/status`, { status: 'done' });
      await load();
    } catch (e) {
      setError((e as Error).message);
    } finally {
      setBusy(null);
    }
  }

  async function snooze(id: string) {
    const days = window.prompt('Snooze for how many days?', '3');
    if (!days) return;
    const n = Number(days);
    if (!Number.isFinite(n) || n <= 0) return;
    setBusy(id);
    try {
      const until = new Date(Date.now() + n * 86400000).toISOString();
      await apiSend('POST', `/follow-up-desk/tasks/${id}/status`, { status: 'snoozed', snoozed_until: until });
      await load();
    } catch (e) {
      setError((e as Error).message);
    } finally {
      setBusy(null);
    }
  }

  async function dismiss(id: string) {
    setBusy(id);
    try {
      await apiSend('POST', `/follow-up-desk/tasks/${id}/status`, { status: 'dismissed' });
      await load();
    } catch (e) {
      setError((e as Error).message);
    } finally {
      setBusy(null);
    }
  }

  const open = tasks.filter((t) => t.status === 'open');
  const snoozed = tasks.filter((t) => t.status === 'snoozed');

  return (
    <div className="fud">
      <style>{CSS}</style>
      <header className="fud-head">
        <div>
          <h1>Divini Follow-Up Desk</h1>
          <p className="fud-sub">What needs a reply, today. System tasks come from real stale opportunities and proposals; add your own anytime.</p>
        </div>
        <button className="fud-btn" onClick={() => setCreating((v) => !v)}>{creating ? 'Cancel' : 'New task'}</button>
      </header>

      {loading && <p className="fud-muted">Loading.</p>}
      {error && <p className="fud-error">{error}</p>}

      {creating && (
        <form className="fud-card fud-form" onSubmit={create}>
          <input placeholder="Task" value={form.title} onChange={(e) => setForm({ ...form, title: e.target.value })} />
          <input placeholder="Note (optional)" value={form.note} onChange={(e) => setForm({ ...form, note: e.target.value })} />
          <input type="date" value={form.due_at} onChange={(e) => setForm({ ...form, due_at: e.target.value })} />
          <button type="submit" className="fud-btn" disabled={busy === 'create'}>{busy === 'create' ? 'Adding.' : 'Add task'}</button>
        </form>
      )}

      <div className="fud-sectiontitle">Open ({open.length})</div>
      {!loading && open.length === 0 && <div className="fud-empty">Nothing needs follow-up right now.</div>}
      <div className="fud-list">
        {open.map((t) => (
          <div className="fud-item" key={t.id}>
            <div className="fud-item-main">
              <div className="fud-item-title">{t.title}</div>
              <div className="fud-item-meta">
                {t.source === 'system' && t.rule_key && <span className="fud-tag">{RULE_LABEL[t.rule_key] ?? t.rule_key}</span>}
                {dueLabel(t) && <span className="fud-due">{dueLabel(t)}</span>}
              </div>
              {t.note && <div className="fud-item-note">{t.note}</div>}
            </div>
            <div className="fud-item-actions">
              <button className="fud-mini" onClick={() => markDone(t.id)} disabled={busy === t.id}>Done</button>
              <button className="fud-mini ghost" onClick={() => snooze(t.id)} disabled={busy === t.id}>Snooze</button>
              <button className="fud-mini ghost" onClick={() => dismiss(t.id)} disabled={busy === t.id}>Dismiss</button>
            </div>
          </div>
        ))}
      </div>

      {snoozed.length > 0 && (
        <>
          <div className="fud-sectiontitle">Snoozed ({snoozed.length})</div>
          <div className="fud-list">
            {snoozed.map((t) => (
              <div className="fud-item snoozed" key={t.id}>
                <div className="fud-item-main">
                  <div className="fud-item-title">{t.title}</div>
                  <div className="fud-item-meta">
                    <span className="fud-due">Until {t.snoozed_until ? new Date(t.snoozed_until).toLocaleDateString() : ''}</span>
                  </div>
                </div>
              </div>
            ))}
          </div>
        </>
      )}
    </div>
  );
}

const CSS = `
.fud { --e:#123c2e; --e2:#1E5D4A; --g:#C9A35B; --ink:#2c2a26; --mut:#6b6459; --ln:#e7e1d6;
  --bg:#fbf9f4; font-family:'Inter',system-ui,sans-serif; color:var(--ink); max-width:760px;
  margin:0 auto; padding:24px 20px 56px; }
.fud *,.fud *::before,.fud *::after { box-sizing:border-box; }
.fud-head { display:flex; justify-content:space-between; align-items:flex-start; gap:14px; flex-wrap:wrap; }
.fud-head h1 { font-size:24px; margin:0 0 6px; color:var(--e); font-weight:800; }
.fud-sub { font-size:14px; color:var(--mut); margin:0; max-width:520px; line-height:1.5; }
.fud-muted { font-size:12px; color:var(--mut); margin:10px 0 0; }
.fud-error { font-size:13px; color:#9a3a28; margin:8px 0; }
.fud-sectiontitle { font-size:13px; font-weight:700; color:var(--e); text-transform:uppercase; letter-spacing:.4px; margin:20px 0 8px; }

.fud-btn { background:var(--e); color:#fff; border:none; border-radius:9px; padding:9px 16px;
  font-size:13.5px; font-weight:600; cursor:pointer; white-space:nowrap; }
.fud-btn:disabled { opacity:.6; cursor:default; }

.fud-card { background:#fff; border:1px solid var(--ln); border-radius:12px; padding:14px 16px; }
.fud-form { display:flex; flex-direction:column; gap:8px; margin-top:16px; }
.fud-form input { border:1px solid var(--ln); border-radius:8px; padding:8px 11px; font-size:13.5px; font-family:inherit; width:100%; }
.fud-form .fud-btn { align-self:flex-start; margin-top:4px; }

.fud-empty { border:1px dashed var(--ln); border-radius:12px; padding:16px; color:var(--mut); font-size:13.5px; }

.fud-list { display:flex; flex-direction:column; gap:8px; }
.fud-item { background:#fff; border:1px solid var(--ln); border-radius:10px; padding:12px 14px; display:flex; justify-content:space-between; align-items:center; gap:10px; flex-wrap:wrap; }
.fud-item.snoozed { opacity:.65; }
.fud-item-title { font-weight:700; font-size:13.5px; color:var(--e); }
.fud-item-meta { display:flex; gap:8px; margin-top:3px; flex-wrap:wrap; }
.fud-tag { font-size:10px; font-weight:700; text-transform:uppercase; letter-spacing:.3px; background:var(--bg); color:var(--e2); border:1px solid var(--ln); border-radius:999px; padding:2px 8px; }
.fud-due { font-size:11px; color:var(--mut); }
.fud-item-note { font-size:12px; color:var(--mut); margin-top:4px; }
.fud-item-actions { display:flex; gap:6px; }
.fud-mini { background:var(--e); color:#fff; border:none; border-radius:7px; padding:6px 11px; font-size:12px; font-weight:600; cursor:pointer; }
.fud-mini.ghost { background:#fff; color:var(--e); border:1px solid var(--ln); }
.fud-mini:disabled { opacity:.6; cursor:default; }

@media(max-width:600px){ .fud { padding:18px 14px 44px; } .fud-head h1 { font-size:20px; } .fud-item { flex-direction:column; align-items:flex-start; } .fud-item-actions { width:100%; } }
`;
